apiVersion: batch/v1
kind: Job
metadata:
  name: builder
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        command:
        - sh
        - -c
        - |
          set -euvx

          /kaniko/executor \
            --context=git://github.com/10hin/spring-on-eks/#0ff9c6cb60c3f906596f50b112c0b40b827da915 \
            --dockerfile=package/Dockerfile \
            --destination=129008548655.dkr.ecr.ap-northeast-1.amazonaws.com/github.com/10hin/spring-on-eks:latest \
            ;
      restartPolicy: Never
      serviceAccountName: builder
  backoffLimit: 3
