apiVersion: batch/v1
kind: Job
metadata:
  name: builder
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        command:
        - sh
        - -c
        - |
          set -euvx

          /kaniko/executor \
            --git=branch=main,single-branch=false,recurse-submodule=false \
            --context=git://github.com/10hin/spring-on-eks/ \
            --dockerfile=package/Dockerfile \
            --destination=129008548655.dkr.ecr.ap-northeast-1.amazonaws.com/github.com/10hin/spring-on-eks:latest \
            ;
      restartPolicy: Never
      serviceAccountName: builder
  backoffLimit: 3
